package guardias;


import java.io.File;
import java.io.PrintStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCargar1 = new javax.swing.JButton();
        jLabelGuardias = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonCrearCalendario = new javax.swing.JButton();
        jLabelYear = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabelMonth = new javax.swing.JLabel();
        jTextFieldMonth = new javax.swing.JTextField();
        jLabelSeed = new javax.swing.JLabel();
        jTextFieldSeed = new javax.swing.JTextField();
        jButtonResidentes = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelAusencia = new javax.swing.JLabel();
        jTextFieldAusencia = new javax.swing.JTextField();
        jButtonAddAusencia = new javax.swing.JButton();
        jButtonRmvAusencia = new javax.swing.JButton();
        jLabelObligatorio = new javax.swing.JLabel();
        jTextFieldObligatorio = new javax.swing.JTextField();
        jButtonAddObligatorio = new javax.swing.JButton();
        jButtonRmvObligatorio = new javax.swing.JButton();

        jButtonCargar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCargar1.setText("Cargar Fichero");
        jButtonCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi analizador (L) ");

        jLabelGuardias.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabelGuardias.setText("Guardias");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setText("\n");
        jScrollPane.setViewportView(jTextArea);

        jButtonCrearCalendario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCrearCalendario.setText("Crear Calendario");
        jButtonCrearCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCalendarioActionPerformed(evt);
            }
        });

        jLabelYear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelYear.setText("YEAR");

        jTextFieldYear.setText("jTextField1");

        jLabelMonth.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMonth.setText("MONTH");

        jTextFieldMonth.setText("jTextField1");

        jLabelSeed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSeed.setText("SEED");

        jTextFieldSeed.setText("jTextField1");

        jButtonResidentes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonResidentes.setText("RESIDENTES");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabelAusencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAusencia.setText("Ausencia");

        jTextFieldAusencia.setText("jTextField4");

        jButtonAddAusencia.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonAddAusencia.setText("+");
        jButtonAddAusencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAusenciaActionPerformed(evt);
            }
        });

        jButtonRmvAusencia.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonRmvAusencia.setText("-");
        jButtonRmvAusencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRmvAusenciaActionPerformed(evt);
            }
        });

        jLabelObligatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObligatorio.setText("Obligatorio");

        jTextFieldObligatorio.setText("jTextField4");

        jButtonAddObligatorio.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonAddObligatorio.setText("+");
        jButtonAddObligatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddObligatorioActionPerformed(evt);
            }
        });

        jButtonRmvObligatorio.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonRmvObligatorio.setText("-");
        jButtonRmvObligatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRmvObligatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAusencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabelObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextFieldAusencia)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jButtonAddAusencia)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonRmvAusencia)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButtonAddObligatorio)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonRmvObligatorio))
                                                    .addComponent(jTextFieldObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCrearCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 39, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(63, 63, 63)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonResidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGuardias, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGuardias)
                    .addComponent(jButtonResidentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAusencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAusencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddAusencia)
                            .addComponent(jButtonRmvAusencia)
                            .addComponent(jButtonAddObligatorio)
                            .addComponent(jButtonRmvObligatorio))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCrearCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSeed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        setSize(new java.awt.Dimension(715, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCargar1ActionPerformed

    private void jButtonCrearCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearCalendarioActionPerformed

    private void jButtonAddAusenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAusenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddAusenciaActionPerformed

    private void jButtonRmvAusenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRmvAusenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRmvAusenciaActionPerformed

    private void jButtonAddObligatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddObligatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddObligatorioActionPerformed

    private void jButtonRmvObligatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRmvObligatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRmvObligatorioActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    /**
     * @param args the command line arguments
     */
	// <editor-fold defaultstate="collapse" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAusencia;
    private javax.swing.JButton jButtonAddObligatorio;
    private javax.swing.JButton jButtonCargar1;
    private javax.swing.JButton jButtonCrearCalendario;
    private javax.swing.JButton jButtonResidentes;
    private javax.swing.JButton jButtonRmvAusencia;
    private javax.swing.JButton jButtonRmvObligatorio;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelAusencia;
    private javax.swing.JLabel jLabelGuardias;
    private javax.swing.JLabel jLabelMonth;
    private javax.swing.JLabel jLabelObligatorio;
    private javax.swing.JLabel jLabelSeed;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldAusencia;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldObligatorio;
    private javax.swing.JTextField jTextFieldSeed;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
	// </editor-fold>
}
